version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized staging model for raw Telegram messages"
    columns:
      - name: message_id
        description: "Unique identifier for the message"
        tests:
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: message_date
        description: "Timestamp when the message was posted"
        tests:
          - not_null
      - name: message_text
        description: "Full text content of the message"
      - name: message_length
        description: "Length of the message text in characters"
      - name: has_media
        description: "Boolean flag indicating if message contains media"
      - name: has_image
        description: "Boolean flag indicating if message has an image (calculated from image_path)"
      - name: image_path
        description: "Relative path to downloaded image file"
      - name: views
        description: "Number of views on the message"
      - name: forwards
        description: "Number of times the message was forwarded"
      - name: loaded_at
        description: "Timestamp when the record was loaded into the database"
